#:kivy 2.2.1

<Header>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.65
        BoxShadow:
            pos: self.pos
            size: root.width, dp(80)
            offset: 0, -10
            blur_radius: 35
            spread_radius: -10, -10
    canvas:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: root.width, dp(80)