#:kivy 2.2.1

<Header>:
    canvas.before:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'
    angle: 90
<CrackContainer2>:
    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        size: root.width, self.height

        RelativeLayout:  # Sử dụng RelativeLayout để định vị logo và label
            size_hint_y: None
            height: dp(100)
            Header:
                top: root.top
                size: root.width, self.height
                RelativeLayout:
                    orientation: 'horizontal'
                    size_hint: None, None
                    size: dp(430), dp(100)  # Điều chỉnh kích thước của phần logo và label
                    valign: 'middle'
                    canvas.before:
                        Color:
                            rgba: (19/255, 98/255, 197/255, 1)  # Màu xanh dương
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Image:
                        size_hint_x: None
                        width: dp(80)
                        pos_hint: {'center_x': 0.2, 'center_y': 0.5}
                        center_y: self.parent.center_y
                        source: 'logo.png'
                        valign: 'middle'
                    Label:
                        font_size: 55
                        pos_hint: {'center_x': 0.6, 'center_y': 0.5}
                        text: "AIOT LAB VN"
                        color: 1, 1, 1, 1
                        bold: True
                        valign: 'middle'

        RelativeLayout:
            orientation:'vertical'            
            size: root.width, 700
           
            Label:
                pos_hint: {"center_x":0.5, "center_y":0.97}
                font_size: 30
                size_hint: None, None 
                text: "CRACK INSPECTOR 360"
                color: 19/255, 98/255, 197/255, 1
                size: root.width, 30
                text_size: self.size
                halign: 'center'
                valign: 'top'
                padding: 10, 0
                bold: True

            Label:
                pos_hint: {"center_x":0.5, "center_y":0.87}
                text: "Quickly evaluate the location and extent of cracks, an algorithm built on the YOLOv8 platform to detect and evaluate different levels of cracks in images. Developed by students of CE and IT departments of international universities."
                size_hint_y: None 
                font_size: 20
                color: 0, 0, 0, 1
                size: root.width, 30
                height: self.texture_size[1]
                text_size: self.width, None
                halign: 'center'
                padding: 10, 0
            
            Label:
                pos_hint: {"center_x":0.5, "center_y":0.75}
                font_size: 30
                size_hint: None, None # Shrink the label size to the text size
                text: "ABOUT US"
                color: 19/255, 98/255, 197/255, 1
                size: root.width, 30
                halign: 'center'
                text_size: self.size
                bold: True

            Label:
                pos_hint: {"center_x":0.5, "center_y":0.7}
                text: "AIoT Lab VN, established in 2022, is a pioneering hub at the forefront of Artificial Intelligence and Internet of Things in Vietnam."
                size_hint_y: None # Shrink the label size to the text size
                font_size: 20
                color: 0, 0, 0, 1
                size: root.width, 30
                height: self.texture_size[1]
                text_size: self.width, None
                halign: 'center'
                padding: 10, 0

            OpenCamera:
                id: camera
                play: False
                opacity: 0

            RoundedButton:
                id: open_cam
                pos_hint: {"center_x":0.5, "center_y":0.6}
                text: 'GET STARTED'
                on_press:
                    self.opacity = 0.5
                on_release:
                    self.opacity = 1
                    app.root.get_screen("second").ids.camera.play = True
                    app.root.current = 'second'
                size_hint: None, None
                size: dp(142), dp(48)
                color: 1, 1, 1, 1
                background_color: 19/255, 98/255, 197/255, 1

<CrackContainer2>:
    start_cam: start_cam
    detect_img: detect_img
    report: report
    
    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        size: root.width, self.height
        RelativeLayout:  
            size_hint_y: None
            height: dp(100)
            Header:
                top: root.top
                size: root.width, self.height
                RelativeLayout:
                    orientation: 'horizontal'
                    size_hint: None, None
                    size: dp(430), dp(100)  # Điều chỉnh kích thước của phần logo và label
                    valign: 'middle'
                    canvas.before:
                        Color:
                            rgba: (19/255, 98/255, 197/255, 1)  
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Image:
                        size_hint_x: None
                        width: dp(80)
                        pos_hint: {'center_x': 0.3, 'center_y': 0.5}
                        center_y: self.parent.center_y
                        source: 'logo2.png'
                        valign: 'middle'
                    Label:
                        font_size: 55
                        pos_hint: {'center_x': 0.6, 'center_y': 0.5}
                        text: "AIOT LAB VN"
                        color: 1, 1, 1, 1
                        bold: True
                        valign: 'middle'
        RelativeLayout:
            OpenCamera:
                id: camera
                play: True
                opacity: 1
            #Detected image
            Image:
                opacity: 0
                id: detect_img
                pos_hint: {"center_x":0.5, "center_y":0.5}
                size_hint: None, None
                width: dp(430)
                height: dp(531)
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            size: 430, 200
            padding: 10
            spacing: 20
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1  # Màu nền #D9D9D9
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Report result:"
                size_hint: None, None
                pos_hint: {'center_y': 0.75}
                size: 430, 40
                font_size: 40
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                bold: True
                halign: 'left'  
        #Result detected on screen (area, score)
            Label:
                id: report
                size_hint: None, None
                pos_hint: {"center_x":0.44, "center_y":0.5}
                font_size: 35
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF  
        RelativeLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size: 430, 170
            padding: 30, 30  # Padding trên và dưới
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1  
                Rectangle:
                    pos: self.pos
                    size: self.size
            Button:
                background_normal: 'gallery-icon.png'  # Đường dẫn đến biểu tượng thư viện
                size_hint: None, None
                size: 160, 160
                pos_hint: {'center_x': 0.25}  # Đặt biểu tượng ở giữa của bên trái
                valign: 'center'
                halign: 'center'
                on_release:
                    camera.opacity = 0
                    detect_img.opacity = 1
                    self.opacity = 1
                    camera.play = False
                    root.compute(root.choose_img())


            Button:
                size_hint: None, None
                size: 85, 85
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                id: start_cam
                on_release:
                    camera.opacity = 0
                    detect_img.opacity = 1
                    self.opacity = 1
                    camera.play = False
                    root.compute(root.take_image())
                canvas.before:
                    Color:
                        rgba: 0.7, 0.7, 0.7, 1  # Màu xám cho nền
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [42, 42, 0, 0]  # Để làm cho cả 4 góc là góc tròn
                    Color:
                        rgba: (19/255, 98/255, 197/255, 1)  # Màu xanh dương cho viền
                    Line:
                        width: 4
                        rectangle: (self.x, self.y, self.width, self.height)

            Button:
                background_normal: 'return-img.png'  # Đường dẫn đến hình ảnh của bạn
                size_hint: None, None
                size: 100, 100
                pos_hint: {'center_x': 0.75, 'center_y': 0.5}
                id: start_cam
                valign: 'center' 
                halign: 'center'
                on_release:
                    camera.play = True
                    camera.opacity = 1
                    detect_img.opacity = 0
                    self.opacity = 1
                    root.remove_img()
                    root.remove_result()

