#:kivy 2.2.1

<Header>: canvas: Color: rgba: (19/255, 98/255, 197/255, 1) Rectangle: pos: self.pos size: root.width, dp(100)
<OpenCamera>:
resolution: (430, 531)
play: True
#keep_ratio: True
orientation: 'portrait'
angle: 90

<CrackContainer1>:
canvas.before:
Color:
rgba: 180, 180, 180, 180
Rectangle:
pos: self.pos
size: self.size

dts
Copy
RelativeLayout:
    orientation:"vertical"
    size: root.width, self.height
    Header:
        top: root.top
        size: root.width, self.height

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(100)

        Image:
            size_hint_x: None
            padding_x: 20
            width: dp(80)  
            source: 'logo2.png'
        Label:
            font_size: 45
            text: "AIOT LAB VN"
            color: 1, 1, 1, 1
            bold: True
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        size: 430, 150
        padding: 10
        spacing            Button:
            id: start_cam
            text: "Start Camera"
            size_hint: 1, None
            height: 50
            on_release: camera.play = True

        Button:
            id: close_cam
            text: "Close Camera"
            size_hint: 1, None
            height: 50
            on_release: camera.play = False

    OpenCamera:
        id: camera
        resolution: (430, 531)

    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: dp(100)
        padding: 10
        spacing: 10

        Button:
            id: detect_img
            text: "Detect"
            size_hint: 1, None
            height: 50
            on_release: root.capture()

        Button:
            text: "Remove Image"
            size_hint: 1, None
            height: 50
            on_release: root.remove_img()

        Label:
            id: report
            text: ""
            font_size: 20
            text_size: self.width, None
            size_hint_y: None
            height: self.texture_size[1] + 20
            valign: 'top'
            halign: 'center'
            padding: 10
            markup: True