#:kivy 2.2.1

<Header>:
    canvas.before:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    canvas:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: root.width, dp(100)

<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'
    angle: 90

<CrackContainer1>:
    close_cam: close_cam
    start_cam: start_cam

    
    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        size: root.width, self.height

        RelativeLayout:  # Sử dụng RelativeLayout để định vị logo và label
            size_hint_y: None
            height: dp(100)
            Header:
                top: root.top
                size: root.width, self.height
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint: None, None
                    size: dp(430), dp(100)  # Điều chỉnh kích thước của phần logo và label
                    valign: 'middle'
                    Image:
                        size_hint_x: None
                        width: dp(80)
                        center_y: self.parent.center_y
                        source: 'logo.png'
                        valign: 'middle'
                    Label:
                        font_size: 45
                        text: "AIOT LAB VN"
                        color: 0, 0, 0, 1
                        bold: True
                        valign: 'middle'
        OpenCamera:
            id: camera
            play: True
            opacity: 1
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            size: 430, 170
            padding: 10
            spacing: 20
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1  # Màu nền #D9D9D9
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Report result:"
                size_hint: None, None
                size: 430, 40
                font_size: 40
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                bold: True
                halign: 'left'  # Căn giữa theo chiều ngang
                valign: 'top' 
