#:kivy 2.2.1

<Header>:
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(100)

            Image:
                size_hint_x: None
                padding_x: 20
                width: dp(80)  
                source: 'logo2.png'

            Label:
                font_size: 45
                text: "CRACK DETECTION APP"
                color: 1, 1, 1, 1
                bold: True

<OpenCamera>:
    resolution: (300, 400)
    play: False
    #keep_ratio: True
    pos_hint:{"x":-0.4, "y":0.09}

<CrackContainer1>:
    name: "first"


    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size


    RelativeLayout:
        orientation:"vertical"
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, self.height




<CrackContainer2>: