#:kivy 2.2.1

<Header>:
    canvas:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: root.width, dp(100)

<OpenCamera>:
    resolution: (300, 400)
    play: False
    #keep_ratio: True
    pos_hint:{"x":-0.4, "y":0.09}

<CrackContainer1>:
    name: "first"


    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size


    RelativeLayout:
        orientation:"vertical"
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, self.height

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(100)

            Image:
                center_x: root.width / 2
                size_hint_x: None
                width: dp(80)  
                source: 'logo2.png'

            Label:
                font_size:45
                text: "CRACK DETECTION APP"
                color: 1, 1, 1, 1
                bold: True


<CrackContainer1>: