#:kivy 2.2.1

<Header>:
    canvas:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: root.width, dp(100)

<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'

<CrackContainer1>:
    name: "first"

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size


    RelativeLayout:
        orientation:"vertical"
        size: root.width, self.height


        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(100)

            Image:
                size_hint_x: None
                padding_x: 20
                width: dp(80)  
                source: 'logo2.png'

            Label:
                font_size: 45
                text: "CRACK DETECTION APP"
                color: 1, 1, 1, 1
                bold: True
            
        OpenCamera:
            id: camera
            play: True
            opacity: 1

<CrackContainer2>: