#:kivy 2.2.1

<RoundedButton@Button>:
	background_color: (0,0,0,0)
	background_normal: ''
    padding: 10
	canvas.before:
		Color:
			rgba: (217/255,217/255,217/255,1)
		RoundedRectangle:
			size: self.size
			pos: self.pos
			radius: [8]

<Header>:
    canvas:
        Color:
            rgba: 19/255, 98/255, 197/255, 1
        Rectangle:
            pos: self.pos
            size: root.width, dp(100)
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        size: self.size
        Image:
            source: 'logo2.png'
            size_hint: None, None
            size: dp(80), dp(80)
            pos_hint: {"center_x": 0.5}
        Label:
            text: "AIOT LAB VN"
            color: 0, 0, 0, 1
            font_size: 24
<OpenCamera>:
    resolution: (300, 400)
    play: False
    #keep_ratio: True
    pos_hint:{"x":-0.4, "y":0.09}


<CrackContainer1>:
    name: "first"
    open_cam: open_cam

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size

    RelativeLayout:
        orientation: "vertical"
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, dp(100)

        Image:
            top: root.top
            size_hint_y: None
            height: dp(40)
            source: 'logo2.png'

        OpenCamera:
            id: camera
            play: False
            opacity: 0

        RoundedButton:
            id: open_cam
            top: root.top - 180
            text: 'Open Camera'
            on_press:
                self.opacity = 0.5
            on_release:
                self.opacity = 1
                app.root.get_screen("second").ids.camera.play = True
                app.root.current = 'second'

            size_hint: None, None
            size: dp(142), dp(48)
            color: 0, 0, 0, 1
            pos: root.x + 10, self.y

<CrackContainer2>:
    name: "second"
    close_cam: close_cam
    start_cam: start_cam
    detect_img: detect_img
    report: report

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size

    RelativeLayout:
        orientation: "vertical"
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, dp(100)

        Image:
            top: root.top
            size_hint_y: None
            height: dp(40)
            source: 'logo2.png'

        OpenCamera:
            id: camera
            play: False
            resolution: (195, 195)
            pos_hint: {'center_x': 0.5, 'center_y': 0.68}

        Label:
            id: report
            font_size: 16
            text_size: self.size
            color: 0, 0, 0, 1
            pos_hint: {"x": 0.2, "y": 0.2}

        RoundedButton:
            canvas.before:
                Color:
                    rgba: (102/255, 178/255, 255/255, 1) # Blue
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                radius: 15
            id: start_cam
            top: root.top - 465
            text: 'Capture Image'
            bold: True
            on_press: self.opacity = 0.5
            on_release:
                self.opacity = 1
                camera.play = False
                root.capture()
            size_hint: None, None
            size: dp(100), dp(30)
            color: 1, 1, 1, 1
            pos: root.x + 10, self.y




