#:kivy 2.2.1

<Header>:
    canvas.before:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'
    angle: 90

<CrackContainer1>:
    start_cam: start_cam
    detect_img: detect_img
    report: report
    
    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        size: root.width, self.height

        RelativeLayout:  # Sử dụng RelativeLayout để định vị logo và label
            size_hint_y: None
            height: dp(100)
            Header:
                top: root.top
                size: root.width, self.height
                RelativeLayout:
                    orientation: 'horizontal'
                    size_hint: None, None
                    size: dp(430), dp(100)  # Điều chỉnh kích thước của phần logo và label
                    valign: 'middle'
                    canvas.before:
                        Color:
                            rgba: (19/255, 98/255, 197/255, 1)  # Màu xanh dương
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Image:
                        size_hint_x: None
                        width: dp(80)
                        pos_hint: {'center_x': 0.3, 'center_y': 0.5}
                        center_y: self.parent.center_y
                        source: 'logo2.png'
                        valign: 'middle'
                    Label:
                        font_size: 55
                        pos_hint: {'center_x': 0.6, 'center_y': 0.5}
                        text: "AIOT LAB VN"
                        color: 1, 1, 1, 1
                        bold: True
                        valign: 'middle'
        OpenCamera:
            id: camera
            play: True
            opacity: 1
        #Detected image
        Image:
            id: detect_img
            pos_hint: {"center_x":0.5, "center_y":0.4}
            size_hint: None, None
            width: dp(250)
            height: dp(250)
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size: 430, 200
            padding: 10
            spacing: 20
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1  # Màu nền #D9D9D9
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Report result:"
                size_hint: None, None
                pos_hint: {'center_y': 0.75}
                size: 430, 40
                font_size: 40
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                bold: True
                halign: 'left'  # Căn giữa theo chiều ngang
        #Result detected on screen (area, score)
        Label:
            id: report
            font_size: 16
            # halign: "left"
            # valign: "bottom"
            text_size: self.size
            color: 0, 0, 0, 1
            pos_hint: {"x": 0.2, "y":0.2}
        RelativeLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size: 430, 170
            padding: 30, 30  # Padding trên và dưới
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1  
                Rectangle:
                    pos: self.pos
                    size: self.size
            Image:
                source: 'gallery-icon.png'  # Đường dẫn đến biểu tượng thư viện
                size_hint: None, None
                size: 160, 160
                pos_hint: {'center_x': 0.25}  # Đặt biểu tượng ở giữa của bên trái
                valign: 'center'
                halign: 'center'
            Button:
                size_hint: None, None
                size: 85, 85
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                id: start_cam
                on_release:
                    self.opacity = 1
                    camera.play = False
                    root.capture()
                canvas.before:
                    Color:
                        rgba: 0.7, 0.7, 0.7, 1  # Màu xám cho nền
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [42, 42, 0, 0]  # Để làm cho cả 4 góc là góc tròn
                    Color:
                        rgba: (19/255, 98/255, 197/255, 1)  # Màu xanh dương cho viền
                    Line:
                        width: 4
                        rectangle: (self.x, self.y, self.width, self.height)

            Image:
                source: 'return-img.png'  # Đường dẫn đến hình ảnh của bạn
                size_hint: None, None
                size: 100, 100
                pos_hint: {'center_x': 0.75, 'center_y': 0.5}

                valign: 'center' 
                halign: 'center'
                on_release:
                    self.opacity = 1
                    root.manager.current = 'first'
                    root.remove_img()
                    root.remove_result()


