#:kivy 2.2.1

<Header>:
    canvas:
        Color:
            rgba: (19/255, 98/255, 197/255, 1)
        Rectangle:
            pos: self.pos
            size: root.width, dp(100)
    

<OpenCamera>:
    resolution: (430, 531)
    play: True
    #keep_ratio: True
    orientation: 'portrait'
    angle: 90

<CrackContainer1>:
    name: "first"

    canvas.before:
        Color:
            rgba: 180, 180, 180, 180
        Rectangle:
            pos: self.pos
            size: self.size


    RelativeLayout:
        orientation:"vertical"
        size: root.width, self.height
        Header:
            top: root.top
            size: root.width, self.height

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(100)

            Image:
                size_hint_x: None
                padding_x: 20
                width: dp(80)  
                source: 'logo2.png'
            Label:
                font_size: 45
                text: "CRACK DETECTION APP"
                color: 1, 1, 1, 1
                bold: True
        OpenCamera:
            id: camera
            play: True
            opacity: 1
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            size: 430, 150
            padding: 10
            spacing: 20
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1  # Màu nền #D9D9D9
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "Result"
                size_hint: None, None
                size: 430, 40
                font_size: 40
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                bold: True
                halign: 'left'  # Căn giữa theo chiều ngang
                valign: 'middle'  # Căn giữa theo chiều dọc
            Label:
                text: "                            Crack predicted accuracy:"
                size_hint: None, None
                size: 430, 20
                font_size: 25
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                halign: 'left'  # Căn giữa theo chiều ngang
                valign: 'middle'  # Căn giữa theo chiều dọc
            Label:
                text: "                   The area of crack is: "
                size_hint: None, None
                size: 430, 20
                font_size: 25
                color: 0, 0, 0, 1  # Màu chữ #FFFFFF
                halign: 'left'  # Căn giữa theo chiều ngang
                valign: 'middle'  # Căn giữa theo chiều dọc
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            size: 430, 70  # Kích thước của phần nút chụp hình và biểu tượng thư viện
            padding: 10, 10  # Padding trên và dưới

            Image:
                source: 'library_icon.png'  # Đường dẫn đến biểu tượng thư viện
                size_hint: None, None
                    size: 120, 120
                    pos_hint: {'center_x': 0.25}  # Đặt biểu tượng ở giữa của bên trái

                Button:
                    size_hint: None, None
                    size: 85, 85  # Kích thước nút chụp hình
                    pos_hint: {'center_x': 0.75}  # Đặt nút chụp hình ở giữa
                    background_normal: 'circle_button.png'  # Hình tròn cho nút chụp hình
                    on_release: root.capture_image()  # Xử lý khi nút chụp hình được nhấn


<CrackContainer2>: